#!/usr/bin/env python3
"""Vendor the three webfonts as base64 into src/styles/fonts.css.

The dashboard ships as one self-contained HTML file that has to render
identically on GitHub Pages, inside an embedded iframe, and from a local
file:// path with no network. Linking Google Fonts would break the last two,
so the latin subsets are inlined once, here, and committed.

Run only when changing typefaces:  python3 web/scripts/fetch-fonts.py
"""
import base64
import os
import re
import urllib.request

UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

FAMILIES = [
    ("Big Shoulders Display", "Big+Shoulders+Display:wght@400..800"),
    ("Public Sans", "Public+Sans:ital,wght@0,400..700;1,400"),
    ("IBM Plex Mono", "IBM+Plex+Mono:wght@400;500;600"),
]

OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "src", "styles", "fonts.css")


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req) as r:
        return r.read()


def main():
    blocks = []
    for label, spec in FAMILIES:
        css = get(f"https://fonts.googleapis.com/css2?family={spec}&display=swap").decode()
        faces = re.findall(r"@font-face\s*\{[^}]*\}", css)
        kept = 0
        for face in faces:
            # latin only — latin-ext/vietnamese/cyrillic would double the payload
            if "U+0000-00FF" not in face:
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", face)
            if not url:
                continue
            b64 = base64.b64encode(get(url.group(1))).decode()
            blocks.append(re.sub(r"url\(https://[^)]+\.woff2\)",
                                 f"url(data:font/woff2;base64,{b64})", face))
            kept += 1
        print(f"{label}: {kept} face(s) inlined")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    header = ("/* Generated by web/scripts/fetch-fonts.py — do not edit by hand.\n"
              "   Latin subsets of Big Shoulders Display, Public Sans and IBM Plex Mono,\n"
              "   inlined so the single-file build renders with no network. */\n")
    with open(OUT, "w") as fh:
        fh.write(header + "\n".join(blocks) + "\n")
    print(f"wrote {os.path.relpath(OUT)}  {os.path.getsize(OUT) / 1024:.0f} KB")


if __name__ == "__main__":
    main()
