import casesJson from './cases.json'
import reportJson from './report.json'
import type { Case, Report } from './types'

/** Both files are generated by `python src/webdata.py` and inlined by Vite,
 *  so the built page needs no server and no fetch. */
export const cases = casesJson as unknown as Case[]
export const report = reportJson as unknown as Report

export * from './types'
